---
title: "How we match goods"
---

# Data-driven, community-actioned

Using the latest census data, we look at the profiles of local schools and child care centres - considering their socioeconomic profile, growth, and other community factors such as welfare receipts to build a picture of where the demand for pre-loved children's clothing, uniforms, toys and equipment might be most appreciated.

<video  controls>
  <source src="TBL vid.mp4" type="video/mp4">
</video>


Our analysis takes place at the "Statistical Area 2" level, which represents roughly a suburb or locality. Using open data sourced from the ABS, ACARA and the Department of Social Services, we have built initial profiles on each community to identify where are the families with means to give and the age of the children in these communities.

As SmallChange rolls out, we will be able to build better matching algorithms by looking at what makes a successful match, as families who give goods will likely have children with similar interests and the right age for matching with a receiving family.